export const genreOptions = [
  'Adventure',
  'Alternative History',
  'Autobiography',
  'Biography',
  'Classics',
  'Contemporary',
  'Crime',
  'Cyberpunk Culinary Arts',
  'Cyberpunk',
  'Dystopian Self-Help',
  'Dystopian',
  'Epic',
  'Existential DIY Home Improvement',
  'Fantasy',
  'Gothic',
  'Graphic Novel',
  'Historical Fiction',
  'Historical',
  'Horror',
  'Humor',
  'Interdimensional Real Estate',
  'Literary Fiction',
  'Magical Realism',
  'Memoir',
  'Mystery',
  'Neo-Victorian Space Opera',
  'Non-Fiction',
  'Paranormal',
  'Philosophical Fiction',
  'Poetry',
  'Post-Apocalyptic',
  'Post-Modern Polka Dot Adventures',
  'Pre-apocalyptic Laundry Folding',
  'Psychological Fiction',
  'Quantum Leapfrog Romance',
  'Romance',
  'Satire',
  'Science Fiction',
  'Speculative Fiction',
  'Steampunk',
  'Suburban Shaman Mysteries',
  'Thriller',
  'Time-Traveling Taxidermy',
  'Urban Fantasy',
  'War',
  'Western',
  'Young Adult',
  "Children's Stories",
]
