export const genreOptions = [
  { label: 'Adventure', id: 'adventure' },
  { label: 'Alternative History', id: 'alternative_history' },
  { label: 'Autobiography', id: 'autobiography' },
  { label: 'Biography', id: 'biography' },
  { label: 'Classics', id: 'classics' },
  { label: 'Contemporary', id: 'contemporary' },
  { label: 'Crime', id: 'crime' },
  { label: 'Cyberpunk Culinary Arts', id: 'cyberpunk_culinary_arts' },
  { label: 'Cyberpunk', id: 'cyberpunk' },
  { label: 'Dystopian Self-Help', id: 'dystopian_self_help' },
  { label: 'Dystopian', id: 'dystopian' },
  { label: 'Epic', id: 'epic' },
  {
    label: 'Existential DIY Home Improvement',
    id: 'existential_diy_home_improvement',
  },
  { label: 'Fantasy', id: 'fantasy' },
  { label: 'Gothic', id: 'gothic' },
  { label: 'Graphic Novel', id: 'graphic_novel' },
  { label: 'Historical Fiction', id: 'historical_fiction' },
  { label: 'Historical', id: 'historical' },
  { label: 'Horror', id: 'horror' },
  { label: 'Humor', id: 'humor' },
  { label: 'Interdimensional Real Estate', id: 'interdimensional_real_estate' },
  { label: 'Literary Fiction', id: 'literary_fiction' },
  { label: 'Magical Realism', id: 'magical_realism' },
  { label: 'Memoir', id: 'memoir' },
  { label: 'Mystery', id: 'mystery' },
  { label: 'Neo-Victorian Space Opera', id: 'neo_victorian_space_opera' },
  { label: 'Non-Fiction', id: 'non_fiction' },
  { label: 'Paranormal', id: 'paranormal' },
  { label: 'Philosophical Fiction', id: 'philosophical_fiction' },
  { label: 'Poetry', id: 'poetry' },
  { label: 'Post-Apocalyptic', id: 'post_apocalyptic' },
  {
    label: 'Post-Modern Polka Dot Adventures',
    id: 'post_modern_polka_dot_adventures',
  },
  {
    label: 'Pre-apocalyptic Laundry Folding',
    id: 'pre_apocalyptic_laundry_folding',
  },
  { label: 'Psychological Fiction', id: 'psychological_fiction' },
  { label: 'Quantum Leapfrog Romance', id: 'quantum_leapfrog_romance' },
  { label: 'Romance', id: 'romance' },
  { label: 'Satire', id: 'satire' },
  { label: 'Science Fiction', id: 'science_fiction' },
  { label: 'Speculative Fiction', id: 'speculative_fiction' },
  { label: 'Steampunk', id: 'steampunk' },
  { label: 'Suburban Shaman Mysteries', id: 'suburban_shaman_mysteries' },
  { label: 'Thriller', id: 'thriller' },
  { label: 'Time-Traveling Taxidermy', id: 'time_traveling_taxidermy' },
  { label: 'Urban Fantasy', id: 'urban_fantasy' },
  { label: 'War', id: 'war' },
  { label: 'Western', id: 'western' },
  { label: 'Young Adult', id: 'young_adult' },
  { label: "Children's Stories", id: 'childrens_stories' },
]
