export const promptOptions = [
  'In a city where music controls the weather, a deaf composer discovers a forbidden melody.',
  "During an eclipse, a child's shadow comes to life, leading them on an adventure into a hidden world.",
  'A librarian discovers that every book in the library tells a different story when read at midnight.',
  'In a village where aging is a choice, the oldest resident has never made their decision.',
  'An astronaut on Mars finds an ancient, alien library with books that change their content every time they are read.',
  'A world where mirrors show not your reflection, but your true self, and a teenager discovers their mirror is empty.',
  'In a society where emotions are bottled and sold, a person incapable of feeling buys an emotion they have never experienced.',
  'On an island where your role in society is determined by the color of the sky when you are born, a child is born under a new, never-before-seen hue.',
  'A gardener grows a mysterious plant that blooms only under the moonlight, revealing secrets to those who witness its flowers.',
  'In a future where dreams are broadcasted as entertainment, one dreamer’s nightmares start to predict the future.',
  'A town cursed to live the same day repeatedly finds that the loop has suddenly skipped a day.',
  'In a world where shadows whisper secrets from the future, a young girl’s shadow falls silent.',
  'A secret society of writers who can alter reality with their pens faces a member who has started rewriting history for their gain.',
  'An underwater city is discovered to be inhabited by descendants of humans who adapted to live beneath the sea.',
  'A clockmaker invents a clock that can rewind time but discovers it alters more than just hours.',
  'In a realm where colors are flavors, a colorblind chef becomes the most sought-after culinary master.',
  'A scientist creates a machine that can translate animals’ thoughts, only to find that his dog is plotting to take over the world.',
  'A world where you can see how many times you’ve passed by a stranger—two people notice their counters are inexplicably high.',
  'In a post-apocalyptic world, a lone traveler finds a city that was completely untouched by the disaster.',
  'A character discovers they can enter paintings and must solve a mystery spreading through famous artworks.',
  'On a planet where night lasts for years at a time, an eternal day suddenly dawns.',
  'A detective realizes the crime scene they are investigating is a meticulous recreation of a scene from their unpublished novel.',
  'A world where your lifespan is determined by your wealth, a poor man discovers he is immortal.',
  'In a kingdom where dragons are kept as pets, a dragonless pauper finds a wild, untamed dragon in the woods.',
  'A technology that allows you to live inside your favorite books is invented, but someone gets trapped in a novel where they don’t belong.',
  'A character finds a phone that can call into the past and speaks to their younger self, altering their present.',
  'A world divided between day and night dwellers, and a child born in the twilight, belonging to neither.',
  'A painter who can bring her paintings to life struggles with her latest creation, which is determined to stay in the canvas.',
  'In a universe where every planet houses a different aspect of human emotion, an explorer lands on a never-before-seen world filled with a new feeling.',
  'A character discovers that the key to time travel lies within specific words spoken at the right moment and place.',
  'In a city where shadows whisper secrets, a young detective finds hers can scream.',
  'On a planet where music controls the elements, a deaf rebel uncovers a silent frequency that can reshape the world.',
  'In a future where memories can be bought and sold, a man with a perfect memory faces a choice that could erase his identity.',
  "In a kingdom where colors determine one's fate, a colorblind girl discovers a hidden palette that could overthrow the monarchy.",
  'On an island where people age backwards, a child seeks the truth about adulthood and the mysteries beyond the sea.',
  'In a society where books are banned, a librarian leads an underground movement to save knowledge from extinction.',
  'On a space station orbiting a dying star, a lone scientist discovers a way to reignite suns but not without personal cost.',
  'In a world where emotions are forbidden, a young empath embarks on a journey to feel everything, even if it means his demise.',
  'At the edge of the universe, a spaceship harbors the last garden, and its keeper must fight to protect it from extinction.',
  'In a realm where time flows backward, an old man searches for his childhood to unlock the secret to immortality.',
  'On a distant planet where rain never stops, a girl with the power to control the weather searches for the sun.',
  'In a world powered by magic, a technologically advanced outsider threatens to disrupt the balance of power.',
  'In a city above the clouds, a ground dweller risks everything to see what lies above.',
  'On an earth where animals can speak, a silent dog is the key to solving a global mystery.',
  "In a reality where humans live in virtual worlds, one person's glitch reveals the truth about their existence.",
  'At a school for the supernatural, a student without powers uncovers a conspiracy threatening both magical and mundane worlds.',
  "In a forest that remembers, a girl with amnesia seeks her past, only to discover she's part of the woods' dark secret.",
  'On a quest to find a city of gold, an explorer discovers the true wealth is the journey itself.',
  'In a land where shadows are stolen, a young thief’s failure to steal a shadow unravels his reality.',
  'At the brink of an interstellar war, a diplomat discovers the enemy is their own forgotten colony.',
  'In a dystopia where dreams are taxed, a dreamer learns how to dream freely, challenging the regime.',
  'On a voyage to find a new earth, a crew member realizes their ship is alive and has its own plans.',
  'In a world where mirrors reflect the soul, a woman with no reflection must uncover her hidden past.',
  'At a crossroads of parallel worlds, a traveler must choose a path knowing each step changes the destination.',
  'In a society where the written word is sacred, a mute child develops a new language that revolutionizes communication.',
  'On a planet where seasons last for generations, a civilization prepares for a season of darkness they may not survive.',
  "In a realm where illusions are reality, a magician's apprentice must uncover the truth behind the magic.",
  "At the end of time, a lone historian races to document the universe's secrets before they fade into oblivion.",
  'In a city that never sleeps, a man who can control dreams is the key to saving the night.',
  'On a quest to resurrect a lost love, a scholar discovers that some things are meant to remain lost.',
  'In a world governed by alchemy, an unskilled novice accidentally creates a potion that could change everything.',
  'At the height of the renaissance, a time traveler seeks to prevent an invention that would alter history.',
  'In a colony on Mars, a rebel uncovers an ancient Martian secret that could determine the fate of two planets.',
  'On a journey to the center of the Earth, explorers find a civilization that challenges their understanding of history.',
  'In a universe where every star is a world, a lost traveler learns that home is a concept, not a place.',
  'At a library of forgotten books, a reader finds a book that writes itself based on the reader’s own story.',
  'In a future where AI governs humanity, one robot discovers empathy, questioning the very rules of its existence.',
  'On a quest for a cure to save his village, a young alchemist learns that the cure lies within the disease.',
  'In a galaxy where light is harvested, a planet in eternal darkness harbors a power that could light up the universe.',
  'At the intersection of magic and technology, a war brews between those who wield them; only a hybrid can broker peace.',
]
